stages:
  - build
  - publish
  - deploy

cache:
  paths:
    - node_modules/

build:
  tags:
    - vfast
  stage: build
  image:
    name: node:16.15.0
  script:
    - npm install
    - npm run build
  only:
    - develop
  artifacts:
    paths:
      - node_modules/

publish:
  tags:
    - vfast
  stage: publish
  before_script:
    - docker version
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build --cache-from $CI_REGISTRY_IMAGE --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA .
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE:latest
    - docker rmi $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA -f || true
    - docker rmi $CI_REGISTRY_IMAGE:latest -f || true
  only:
    - develop

deploy:
  tags:
    - vfast
  stage: deploy
  only:
    - develop
  before_script:
    - apk update && apk add openssh-client bash
  script:
    - eval $(ssh-agent -s)
    - bash -c 'ssh-add <(echo "$SSH_PRIVATE_KEY")'
    - mkdir -p ~/.ssh
    - ssh-keyscan -H -p $SSH_PORT $SSH_SERVER_IP >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - >
      ssh $SSH_USER@$SSH_SERVER_IP -p $SSH_PORT
      "cat ~/.kube/vultr-config > ~/.kube/config;
      kubectl -n vfast-soft rollout restart deployment/vfast-soft-deployment;"
