import "../styles/globals.css";
import Header from "../layout/Header";
import type { AppProps } from "next/app";
import ScrollBtn from "../layout/ScrollBtn";
import Footer from "../layout/Footer";
import Head from "next/head";

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>V-FAST TECH CO.,LTD</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta
          id="metaDescription"
          name="description"
          content="Công ty Giải pháp Công nghệ V-FAST cung cấp một loạt các giải pháp công nghệ đáp ứng các nhu cầu cụ thể của khách hàng làm việc tại nhiều tổ chức cũng như các doanh nghiệp kinh doanh."
        ></meta>
        <meta
          property="og:description"
          content="Công ty Giải pháp Công nghệ V-FAST cung cấp một loạt các giải pháp công nghệ đáp ứng các nhu cầu cụ thể của khách hàng làm việc tại nhiều tổ chức cũng như các doanh nghiệp kinh doanh."
        ></meta>
        <meta property="og:type" content="website"></meta>
        <meta property="og:url" content="https://vfastsoft.com/"></meta>
        <meta
          property="og:image"
          content="https://vfastsoft.com/logo-vfast.png"
        ></meta>
        <meta property="og:image:width" content="250"></meta>
        <meta property="og:image:height" content="250"></meta>
        <meta property="og:image:type" content="image/jpeg"></meta>
      </Head>
      <Header />
      <Component {...pageProps} />
      <ScrollBtn />
      <Footer />
    </>
  );
}

export default MyApp;
